quant:
    a_qconfig:
        quantizer: LSQFakeQuantize
        observer: MSEObserver
        bit: 4
        symmetric: False
        ch_axis: -1
    w_qconfig:
        quantizer: AdaRoundFakeQuantize
        observer: MSEObserver
        bit: 2
        symmetric: False
        # self.ch_axis != -1: fake_quantize_per_channel_affine
        ch_axis: 0
    calibrate: 1024
    recon:
        batch_size: 32
        scale_lr: 4.0e-5
        warm_up: 0.2
        weight: 0.01
        iters: 20000
        b_range: [20, 2]
        keep_gpu: True
        round_mode: learned_hard_sigmoid
        drop_prob: 0.5
model:
    type: resnet101
    kwargs:
        num_classes: 1000
    path: /home/u2208283129/CalibQuant-R101/model_zoo/resnet101_imagenet.pth
data:
    type: imagenet
    path: /home/u2208283129/CalibQuant-R101/imagenet
    batch_size: 256
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
process:
    seed: 1005
